version: '3'
services:
  db:
    hostname: drupal-db
    container_name: drupal-db
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  drupal:
    depends_on:
      - db
    hostname: drupal
    command: mkdir ./data/drupal/sites/default; touch ./data/drupal/sites/default/settings.php
    container_name: drupal
    image: drupal:8-apache
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./data/drupal/modules:/var/www/html/modules
      - ./data/drupal/profiles:/var/www/html/profiles
      - ./data/drupal/themes:/var/www/html/themes
      - ./data/drupal/sites:/var/www/html/sites

